import type { Metadata } from "next";
import "./globals.css";
import { Footer, NavbarUser } from "@/components";


export const metadata: Metadata = {
  title: "Stickerfly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative">
        <NavbarUser />
        {children}
        <Footer />
      </body>
    </html>
  );
}
