// import type { Metadata } from "next";
// import "./globals.css";
// import { Footer, Navbar } from "@/components";


// export const metadata: Metadata = {
//   title: "Stickerfly",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className="relative">
//         <Navbar />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }
// layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Footer, Navbar, LoggedInNavbar } from "@/components";
import { AuthProvider, useAuth } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Stickerfly",
  description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  const { isAuthenticated } = useAuth();

  return (
    <html lang="en">
      <body className="relative">
        {isAuthenticated ? <LoggedInNavbar /> : <Navbar />}
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <Layout>{children}</Layout>
    </AuthProvider>
  );
}